WalkieTechieApp/urls.py
from __future__ import absolute_import

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^u/', include('accounts.urls', namespace='accounts')),
    url(r'^p/', include('posts.urls', namespace='posts')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(
        r'^users/$',
        views.ListAccountView.as_view(),
        name='user_list'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/$',
        views.DetailAccountView.as_view(),
        name='profile'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/update/$',
        views.UpdateAccountView.as_view(),
        name='update'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/update/password/$',
        views.ChangePasswordView.as_view(),
        name='change_password'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/followers$',
        views.FollowersListView.as_view(),
        name='followers'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/following/$',
        views.FollowingListView.as_view(),
        name='following'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/follow/$',
        views.follow_view,
        name='follow'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/unfollow/$',
        views.unfollow_view,
        name='unfollow'
    ),
]

posts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'create/$',
        views.CreatePostView.as_view(),
        name='create'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/$',
        views.DetailPostView.as_view(),
        name='view'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/update/$',
        views.UpdatePostView.as_view(),
        name='update'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/delete/$',
        views.DeletePostView.as_view(),
        name='delete'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/like/$',
        views.like_post_view,
        name='like'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/unlike/$',
        views.unlike_post_view,
        name='unlike'
    ),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}WalkieTechie PhotoApp{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            padding-bottom: 20px;
            padding-top: 70px;
        }
        .messages {
            list-style: none;
        }
        .red, .red:hover, .red:visited,
        .red:active, .red:focus, .red:link {
            color: #d9534f;
        }
    </style>
    {% block css %}{% endblock css %}
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">WalkieTechie PhotoApp</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{{ user.get_absolute_url }}">{{ user.username }}</a></li>
                        <li><a href="{% url 'posts:create' %}">Create Post</a></li>
                        <li><a href="{% url 'accounts:user_list' %}">List of Users</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h1>{% block headline %}{% endblock headline %}</h1>

        {% block content %}{% endblock content %}
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock js %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>wall</h1>
        {% for post in posts  %}
            {% include 'posts/post.html' %}
        {% endfor %}
    {% else %}
        <p>Welcome, new user. Please log in.</p>
    {% endif %}
{% endblock %}