WalkieTechieApp/urls.py
from __future__ import absolute_import

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^u/', include('accounts.urls', namespace='accounts')),
    url(r'^p/', include('posts.urls', namespace='posts')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(
        r'^users/$',
        views.ListAccountView.as_view(),
        name='user_list'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/$',
        views.DetailAccountView.as_view(),
        name='profile'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/update/$',
        views.UpdateAccountView.as_view(),
        name='update'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/update/password/$',
        views.ChangePasswordView.as_view(),
        name='change_password'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/followers$',
        views.FollowersListView.as_view(),
        name='followers'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/following/$',
        views.FollowingListView.as_view(),
        name='following'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/follow/$',
        views.follow_view,
        name='follow'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/unfollow/$',
        views.unfollow_view,
        name='unfollow'
    ),
]

posts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'create/$',
        views.CreatePostView.as_view(),
        name='create'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/$',
        views.DetailPostView.as_view(),
        name='view'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/update/$',
        views.UpdatePostView.as_view(),
        name='update'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/delete/$',
        views.DeletePostView.as_view(),
        name='delete'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/like/$',
        views.like_post_view,
        name='like'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/unlike/$',
        views.unlike_post_view,
        name='unlike'
    ),
]

posts/models.py
import string as str
from random import choice

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible

from accounts.models import User


def generate_id():
        n = 10
        random = str.ascii_uppercase + str.ascii_lowercase + str.digits
        return ''.join(choice(random) for _ in range(n))


@python_2_unicode_compatible
class Post(models.Model):
    author = models.ForeignKey(User, related_name='post')
    slug = models.SlugField(unique=True, max_length=10, default=generate_id)
    photo = models.FileField(upload_to='posts_photo')
    caption = models.CharField(max_length=50, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Posts'
        ordering = ['-date_created', ]

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('posts:view', kwargs={'slug': self.slug})


@python_2_unicode_compatible
class Like(models.Model):
    post = models.ForeignKey(Post, related_name='liked_post')
    user = models.ForeignKey(User, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

posts/forms.py
from __future__ import absolute_import

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

from .models import Post


class UpdatePostForm(forms.ModelForm):
    class Meta:
        fields = ('caption', )
        model = Post

    def __init__(self, *args, **kwargs):
        super(UpdatePostForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'caption',
            Submit('update', 'Update', css_class='btn primary')
        )


class CreatePostForm(forms.ModelForm):
    class Meta:
        fields = ('photo', 'caption', )
        model = Post

    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'photo',
            'caption',
            Submit('post', 'Post', css_class='btn primary')
        )

posts/views.py
from __future__ import absolute_import

from django.contrib.auth.decorators import login_required
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.http import HttpResponseRedirect

from braces import views

from .models import Post, Like
from .forms import CreatePostForm, UpdatePostForm
from .helpers import get_post


class DetailPostView(
        views.LoginRequiredMixin,
        generic.DetailView
):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(DetailPostView, self).get_context_data(**kwargs)
        context['post'] = get_post(self.kwargs['slug'])

        return context


class CreatePostView(
        views.LoginRequiredMixin,
        generic.CreateView
):
    model = Post
    form_class = CreatePostForm
    template_name = 'posts/post_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super(CreatePostView, self).form_valid(form)


class UpdatePostView(
        views.LoginRequiredMixin,
        views.FormValidMessageMixin,
        generic.UpdateView
):
    model = Post
    form_valid_message = 'Successfully updated your post.'
    form_class = UpdatePostForm
    template_name = 'posts/post_form.html'

    def get(self, request, *args, **kwargs):
        post = Post.objects.get(slug=kwargs['slug'])

        if (post.author != request.user):
            messages.warning(
                request,
                'You don\'t have permission to update this post.',
            )
            return HttpResponseRedirect(
                reverse_lazy(
                    'posts:view',
                    kwargs={'slug': kwargs['slug']}
                )
            )
        else:
            return super(UpdatePostView, self).get(request, *args, **kwargs)


class DeletePostView(
        views.LoginRequiredMixin,
        views.FormValidMessageMixin,
        generic.DeleteView
):
    model = Post
    form_valid_message = 'Successfully deleted your post.'
    success_url = reverse_lazy('home')
    template_name = 'posts/post_delete.html'

    def get(self, request, *args, **kwargs):
        post = Post.objects.get(slug=kwargs['slug'])

        if (post.author != request.user):
            messages.warning(
                request,
                'You don\'t have permission to delete this post.',
            )
            return HttpResponseRedirect(
                reverse_lazy(
                    'posts:view',
                    kwargs={'slug': kwargs['slug']}
                )
            )
        else:
            return super(DeletePostView, self).get(request, *args, **kwargs)


@login_required
def like_post_view(request, *args, **kwargs):
    try:
        post = Post.objects.get(slug=kwargs['slug'])

        _, created = Like.objects.get_or_create(post=post, user=request.user)

        if not created:
            messages.warning(
                request,
                'You\'ve already liked the post.'
            )
    except Post.DoesNotExist:
        messages.warning(
            request,
            'Post does not exist'
        )

    return HttpResponseRedirect(
        reverse_lazy(
            'posts:view',
            kwargs={'slug': kwargs['slug']}
        )
    )


@login_required
def unlike_post_view(request, *args, **kwargs):
    try:
        like = Like.objects.get(
            post__slug=kwargs['slug'],
            user=request.user
        )
    except Like.DoesNotExist:
        messages.warning(
            request,
            'You didn\'t like the post.'
        )
    else:
        like.delete()

    return HttpResponseRedirect(
        reverse_lazy(
            'posts:view',
            kwargs={'slug': kwargs['slug']}
        )
    )

posts/templates/posts/likers.html
<div class="modal fade" id="{{ post.slug }}_likers_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Likers</h4>
            </div>
            <div class="modal-body">
                {% for liker in post.liker %}
                    <a href="{% url 'accounts:profile' liker.username %}"><h1>{{ liker.username }}</h1></a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

posts/templates/posts/post.html
<div id="{{ post.slug }}" class="panel panel-default">
    <div class="panel-heading">
        <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a> |
        <a href="{% url 'posts:view' post.slug %}">{{ post.date_created|timesince }}</a>
        {% if user ==  post.author %}
            | <a href="{% url 'posts:update' post.slug %}">Update</a> |
            <a href="{% url 'posts:delete' post.slug %}">Delete</a>
        {% endif %}
    </div>
    <div class="panel-body">
        <img src="{{ post.photo.url }}" alt="{{ post.caption }}" width="500px" height="500px" />
        <p>{{ post.caption }}</p>
    </div>
    <div class="panel-footer">
        {% if post.liker|length %}
            <a href="#" data-toggle="modal" data-target="#{{ post.slug }}_likers_modal">Likes: {{ post.liker|length }}</a>
            {% include 'posts/likers.html' %}
        {% else %}
            <p>Be the first to like this.</p>
        {% endif %}
        <div class="input-group">
            {% if user in post.liker %}
                <a href="{% url 'posts:unlike' post.slug %}" class="input-group-addon btn btn-default red"><span class="glyphicon glyphicon-heart" id="comment"></span></a>
            {% else %}
                <a href="{% url 'posts:like' post.slug %}" class="input-group-addon btn btn-default"><span class="glyphicon glyphicon-heart" id="comment"></span></a>
            {% endif %}
        <input type="text" class="form-control" placeholder="Add a comment..." aria-describedby="comment">
        </div>
    </div>
</div>

posts/templates/posts/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <img src="{{ post.photo.url }}" alt="{{ post.caption.url }}">
    <p>{{ post.caption }}</p>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this post?</p>
        <input type="submit" name="yes" value="Yes" class="btn btn-success" />
        <a href="{% url 'posts:view' post %}" class="btn btn-danger">Cancel</a>
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.author.name }} on WalkieTechieApp: "{{ post.caption }}"{% endblock %}

{% block content %}
    {% include 'posts/post.html' %}
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    {% crispy form %}
{% endblock %}